version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: nest_pg
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bonghee857
      POSTGRES_DB: nest-play-ground
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
